Add files via upload

diff --git a/config/_common/v7.0.1/ramdisk-002-init-script.patch b/config/_common/v7.0.1/ramdisk-002-init-script.patch
--- a/config/_common/v7.0.1/ramdisk-002-init-script.patch
+++ b/config/_common/v7.0.1/ramdisk-002-init-script.patch
@@ -9,12 +9,29 @@
  UmountRoot()
  {
  	grep "^${RootDevice}" /proc/mounts && /bin/umount -f ${Mnt}
-@@ -155,6 +155,8 @@ fi
+@@ -59,5 +61,6 @@
+    fi
+ 
++   (/bin/sh /exts/exec.sh load_kmods && /bin/sh /exts/exec.sh on_jrExit_scripts && echo "Extensions processed") || Exit 99 "jrExit ext init exec failure"
+ 	UmountRoot
+ 
+    exit $1
+ }
+@@ -155,6 +158,8 @@
  # insert basic USB modules for detect f401/FDT
  echo "Insert basic USB modules..."
  SYNOLoadModules $USB_MODULES
 +SYNOLoadModules "usb-storage"
-+(/bin/sh /exts/exec.sh load_kmods && /bin/sh /exts/exec.sh on_boot_scripts && echo "Extensions processed") || Exit 99 "rp ext init exec failure"
++(/bin/sh /exts/exec.sh load_kmods && /bin/sh /exts/exec.sh on_boot_scripts && echo "Extensions processed") || Exit 99 "boot ext init exec failure"
  
  # insert Etron USB3.0 drivers
  
+@@ -209,6 +214,8 @@
+        fi
+ fi
+ 
++(/bin/sh /exts/exec.sh load_kmods && /bin/sh /exts/exec.sh on_patches_scripts && echo "Extensions processed") || Exit 99 "patches ext init exec failure"
++
+ if [ "$SupportDualhead" = "yes" ]; then
+    # Run HA script
+ 	/etc.defaults/AHAtasks check_stage
